name: goreleaser

on:
  push:
    branches: [ master ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
        
      -
        name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Unshallow
        run: git fetch --prune --unshallow
        
      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Copy domains.yml
        run: |
          cp domains.yml.example domains.yml

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -race ./...

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
